
# SE ELIMINA LOS ESPACIOS

for (i in names(tod0)) {
  if(class(tod0[, i]) %in% c("factor", "character")){
    tod0[, i] <- trimws(tod0[, i])
  }
}

for (i in names(tod1)) {
  if(class(tod1[, i]) %in% c("factor", "character")){
    tod1[, i] <- trimws(tod1[, i])
  }
}

# COLOCAR LOS NOMBRES A LOS TITULOS

tod00 <- rename(tod0, "BANCO"="V1","ID"="V2","PRIMER_NOMBRE"="V3","SEGUNDO_NOMBRE"="V4","PRIMER_APELLIDO"="V5","SEGUNDO_APELLIDO"="V6","NOMBRE_CLIENTE"="V7","TIPO_CLIENTE"="V8","RIF_CI"="V9","CODIGO_AGENCIA"="V10","NOMBRE_AGENCIA"="V11","CODIGO_EJECUTIVO"="V12","NOMBRE_EJECUTIVO"="V13","TIPO_BANCA"="V14","ZONA_AREA"="V15","ID_GRUPO_ECONOMICO"="V16","GRUPO_ECONOMICO"="V17","MONTO_ACTIVO_GRUPO_ECONOMICO"="V18","PRESTAMO"="V19","PROPUESTA"="V20","MONTO_ORIGINAL"="V21","SALDO_ACTUAL"="V22","MONTO_VIGENTE"="V23","MONTO_REESTRUCTURADO"="V24","MONTO_VENCIDO"="V25","MONTO_LITIGIO"="V26","MONTO_INMOVILIZADO"="V27","DIAS_VENCIDOS"="V28","CANTIDAD_CUOTAS_VENCIDAS_COMERCIAL"="V29","ESTATUS_COMERCIAL_CREDITO"="V30",	"CANTIDAD_PRORROGAS"="V31","FECHA_ULTIMA_PRORROGA"="V32","CLASIFICACION_RIESGO"="V33","PCT_PROVISION"="V34","MONTO_PROVISION_ESPECIFICA"="V35","MONTO_PROVISION_ESPECIFICA_INTERESES"="V36","CUENTA_CONTABLE"="V37","DESCRIPCION_CUENTA_CONTABLE"="V38","ESTATUS_CONTABLE"="V39","DESCRIPCION_ESTATUS_CONTABLE"="V40","TIPO_PRODUCTO"="V41","PRODUCTO_DESCRIPCION"="V42","SUB_PRODUCTO"="V43","SUB_PRODUCTO_DESCRIPCION"="V44","FECHA_LIQUIDACION"="V45","FECHA_VENCIMIENTO_ACTUAL"="V46","FECHA_VENCIMIENTO_ORIGINAL"="V47","PERIODICIDAD"="V48","PERIODICIDAD_CANT"="V49","FECHA_CANCELACION_ULTIMA_CUOTA"="V50","FECHA_CANCELACION_ULTIMA_CUOTA_CAPITAL"="V51","FECHA_VENCIMIENTO_PROX_CUOTA"="V52","MONTO_PROX_CUOTA"="V53","CUOTA_PRINCIPAL"="V54","CUOTA_INTERESES"="V55","OTROS_CARGOS"="V56","CICLO_CAPITAL"="V57","FECHA_DE_CUOTA_PRINCIPAL"="V58","CICLO_INTERESES"="V59","FECHA_CUOTA_INTERESES"="V60","TASA_INTERES"="V61","TIPO_CALCULO_INTERESES"="V62","SALDO_INTERES"="V63","RENDIMIENTOS_COBRAR_VIGENTES"="V64","RENDIMIENTOS_COBRAR_VENCIDOS"="V65","INTERESES_COBRAR_CUENTA_ORDEN"="V66","INTERESES_COBRADOS_ANTICIPADOS"="V67","TIPO_GARANTIA"="V68","DESCRIPCION_GARANTIA"="V69","REFERENCIA_GARANTIA"="V70","MONTO_GARANTIA"="V71","MONEDA"="V72","LINEA_CREDITO"="V73","LINEA_CREDITO_UTILIZADA"="V74","LINEA_CREDITO_DISPONIBLE"="V75","TIPO_LINEA_CREDITO"="V76",
                "DESCRIPCION_TIPO_LINEA_CREDITO"="V77","FECHA_VENCIMIENTO_LINEA_CREDITO"="V78","CUENTA_DEBITO_REPAGO"="V79","TIPO_CUENTA_DEBITO_REPAGO"="V80","SALDO_DISPONIBLE"="V81","PROMEDIO_TRIMESTRAL_CUENTA"="V82","CODIGO_ACTIVIDAD_ECONOMICA"="V83","DESCRIPCION_ACTIVIDAD_ECONOMICA"="V84","SECTOR_ECONOMICO"="V85","CODIGO_DESTINO_FONDOS"="V86","DESCRIPCION_CODIGO_DESTINO_FONDOS"="V87","FECHA_CONSTITUCION_NACIMIENTO"="V88","FECHA_VIGENCIA_VENCIMIENTO"="V89","NUMERO_EMPLEADOS"="V90","FECHA_ULTIMO_EEFF_AUDITADO"="V91","MONTO_INGRESOS_VENTAS_ANUALES"="V92","MONTO_PATRIMONIO"="V93","MONTO_MAXIMO_RIESGO_ASUMIDO"="V94","REFERENCIA_CARTA_CREDITO"="V95","TIPO_MODULO"="V96","CIUDAD"="V97","ESTADO"="V98","CAPITAL_PAGADO"="V99","CODIGO_SEXO"="V100",	"SEXO_DESCRIPCION"="V101","ESTADO_CIVIL"="V102","ESTADO_CIVIL_DESCRIPCION"="V103","NACIONALIDAD"="V104","CARGAS_FAMILIARES"="V105","TIPO_VIVIENDA"="V106","ANTIGUEDAD_RESIDENCIA"="V107","LUGAR_NACIMIENTO"="V108","CODIGO_NIVEL_EDUCACION"="V109","DESCRIPCION_NIVEL_EDUCACION"="V110",
                "CODIGO_PROFESION"="V111","DESCRIPCION_PROFESION"="V112","FUENTE_INGRESOS"="V113","DESCRIPCION_FUENTE_INGRESOS"="V114","OCUPACION"="V115","DESCRIPCION_OCUPACION"="V116","ACCIONISTA"="V117","PCT_ACCIONARIO"="V118","ID_ACCIONISTA"="V119","ADMINISTRACION"="V120","CARGO"="V121","ID_ADMINISTRADOR"="V122","SOLVENCIA"="V123","LIQUIDEZ"="V124","CAPITAL_TRABAJO"="V125","DIAS_MANO_COBRANZA"="V126","DIAS_MANO_CUENTAS_PAGAR"="V127","DIAS_MANO_INVENTARIO"="V128","DIAS_CICLO_ECONOMICO"="V129","APALANCAMIENTO"="V130","VENTAS_PASIVO_CIRCULANTE"="V131","AUTONOMIA_FINANCIERA"="V132","EBITDA"="V133","DEUDA_BANCARIA_VENTAS"="V134","RENTABILIDAD_UTILIDAD_NETA_VTAS"="V135","ROE_UTILIDAD_NETA_PATRIMONIO"="V136","PASIVO_CIRCULANTE_VENTAS"="V137","PASIVO_TOTAL_VENTAS"="V138","VARIACION_VENTAS"="V139","ESTRUCTURA_COSTOS_GASTOS"="V140","ACTIVO_CIRCULANTE_TOTAL_ACTIVO"="V141","INMUEBLES_TOTAL_ACTIVO"="V142","INV_LIQUIDAS_TOTAL_ACTIVO"="V143","INGRESO_ANUAL_PASIVO_CIRCULANTE"="V144","INGRESO_ANUAL_SERVICIO_DEUDA"="V145",
                "TOTAL_PASIVO_TOTAL_ACTIVO"="V146","INMUEBLES_TOTAL_PASIVO"="V147","FECHA_VENCIMIENTO_DOCUMENTO_PAGARE"="V148","FECHA_VENCIMIENTO_ACTUAL_PAGARE"="V149","NUMERO_PRORROGAS_PAGARE"="V150","CODIGO_SECTOR_ECONOMICO"="V151","VACIO"="V152"
)

tod11 <- rename(tod1, "BANCO"="V1","ID"="V2","PRIMER_NOMBRE"="V3","SEGUNDO_NOMBRE"="V4","PRIMER_APELLIDO"="V5","SEGUNDO_APELLIDO"="V6","NOMBRE_CLIENTE"="V7","TIPO_CLIENTE"="V8","RIF_CI"="V9","CODIGO_AGENCIA"="V10","NOMBRE_AGENCIA"="V11","CODIGO_EJECUTIVO"="V12","NOMBRE_EJECUTIVO"="V13","TIPO_BANCA"="V14","ZONA_AREA"="V15","ID_GRUPO_ECONOMICO"="V16","GRUPO_ECONOMICO"="V17","MONTO_ACTIVO_GRUPO_ECONOMICO"="V18","PRESTAMO"="V19","PROPUESTA"="V20","MONTO_ORIGINAL"="V21","SALDO_ACTUAL"="V22","MONTO_VIGENTE"="V23","MONTO_REESTRUCTURADO"="V24","MONTO_VENCIDO"="V25","MONTO_LITIGIO"="V26","MONTO_INMOVILIZADO"="V27","DIAS_VENCIDOS"="V28","CANTIDAD_CUOTAS_VENCIDAS_COMERCIAL"="V29","ESTATUS_COMERCIAL_CREDITO"="V30",	"CANTIDAD_PRORROGAS"="V31","FECHA_ULTIMA_PRORROGA"="V32","CLASIFICACION_RIESGO"="V33","PCT_PROVISION"="V34","MONTO_PROVISION_ESPECIFICA"="V35","MONTO_PROVISION_ESPECIFICA_INTERESES"="V36","CUENTA_CONTABLE"="V37","DESCRIPCION_CUENTA_CONTABLE"="V38","ESTATUS_CONTABLE"="V39","DESCRIPCION_ESTATUS_CONTABLE"="V40","TIPO_PRODUCTO"="V41","PRODUCTO_DESCRIPCION"="V42","SUB_PRODUCTO"="V43","SUB_PRODUCTO_DESCRIPCION"="V44","FECHA_LIQUIDACION"="V45","FECHA_VENCIMIENTO_ACTUAL"="V46","FECHA_VENCIMIENTO_ORIGINAL"="V47","PERIODICIDAD"="V48","PERIODICIDAD_CANT"="V49","FECHA_CANCELACION_ULTIMA_CUOTA"="V50","FECHA_CANCELACION_ULTIMA_CUOTA_CAPITAL"="V51","FECHA_VENCIMIENTO_PROX_CUOTA"="V52","MONTO_PROX_CUOTA"="V53","CUOTA_PRINCIPAL"="V54","CUOTA_INTERESES"="V55","OTROS_CARGOS"="V56","CICLO_CAPITAL"="V57","FECHA_DE_CUOTA_PRINCIPAL"="V58","CICLO_INTERESES"="V59","FECHA_CUOTA_INTERESES"="V60","TASA_INTERES"="V61","TIPO_CALCULO_INTERESES"="V62","SALDO_INTERES"="V63","RENDIMIENTOS_COBRAR_VIGENTES"="V64","RENDIMIENTOS_COBRAR_VENCIDOS"="V65","INTERESES_COBRAR_CUENTA_ORDEN"="V66","INTERESES_COBRADOS_ANTICIPADOS"="V67","TIPO_GARANTIA"="V68","DESCRIPCION_GARANTIA"="V69","REFERENCIA_GARANTIA"="V70","MONTO_GARANTIA"="V71","MONEDA"="V72","LINEA_CREDITO"="V73","LINEA_CREDITO_UTILIZADA"="V74","LINEA_CREDITO_DISPONIBLE"="V75","TIPO_LINEA_CREDITO"="V76",
                "DESCRIPCION_TIPO_LINEA_CREDITO"="V77","FECHA_VENCIMIENTO_LINEA_CREDITO"="V78","CUENTA_DEBITO_REPAGO"="V79","TIPO_CUENTA_DEBITO_REPAGO"="V80","SALDO_DISPONIBLE"="V81","PROMEDIO_TRIMESTRAL_CUENTA"="V82","CODIGO_ACTIVIDAD_ECONOMICA"="V83","DESCRIPCION_ACTIVIDAD_ECONOMICA"="V84","SECTOR_ECONOMICO"="V85","CODIGO_DESTINO_FONDOS"="V86","DESCRIPCION_CODIGO_DESTINO_FONDOS"="V87","FECHA_CONSTITUCION_NACIMIENTO"="V88","FECHA_VIGENCIA_VENCIMIENTO"="V89","NUMERO_EMPLEADOS"="V90","FECHA_ULTIMO_EEFF_AUDITADO"="V91","MONTO_INGRESOS_VENTAS_ANUALES"="V92","MONTO_PATRIMONIO"="V93","MONTO_MAXIMO_RIESGO_ASUMIDO"="V94","REFERENCIA_CARTA_CREDITO"="V95","TIPO_MODULO"="V96","CIUDAD"="V97","ESTADO"="V98","CAPITAL_PAGADO"="V99","CODIGO_SEXO"="V100",	"SEXO_DESCRIPCION"="V101","ESTADO_CIVIL"="V102","ESTADO_CIVIL_DESCRIPCION"="V103","NACIONALIDAD"="V104","CARGAS_FAMILIARES"="V105","TIPO_VIVIENDA"="V106","ANTIGUEDAD_RESIDENCIA"="V107","LUGAR_NACIMIENTO"="V108","CODIGO_NIVEL_EDUCACION"="V109","DESCRIPCION_NIVEL_EDUCACION"="V110",
                "CODIGO_PROFESION"="V111","DESCRIPCION_PROFESION"="V112","FUENTE_INGRESOS"="V113","DESCRIPCION_FUENTE_INGRESOS"="V114","OCUPACION"="V115","DESCRIPCION_OCUPACION"="V116","ACCIONISTA"="V117","PCT_ACCIONARIO"="V118","ID_ACCIONISTA"="V119","ADMINISTRACION"="V120","CARGO"="V121","ID_ADMINISTRADOR"="V122","SOLVENCIA"="V123","LIQUIDEZ"="V124","CAPITAL_TRABAJO"="V125","DIAS_MANO_COBRANZA"="V126","DIAS_MANO_CUENTAS_PAGAR"="V127","DIAS_MANO_INVENTARIO"="V128","DIAS_CICLO_ECONOMICO"="V129","APALANCAMIENTO"="V130","VENTAS_PASIVO_CIRCULANTE"="V131","AUTONOMIA_FINANCIERA"="V132","EBITDA"="V133","DEUDA_BANCARIA_VENTAS"="V134","RENTABILIDAD_UTILIDAD_NETA_VTAS"="V135","ROE_UTILIDAD_NETA_PATRIMONIO"="V136","PASIVO_CIRCULANTE_VENTAS"="V137","PASIVO_TOTAL_VENTAS"="V138","VARIACION_VENTAS"="V139","ESTRUCTURA_COSTOS_GASTOS"="V140","ACTIVO_CIRCULANTE_TOTAL_ACTIVO"="V141","INMUEBLES_TOTAL_ACTIVO"="V142","INV_LIQUIDAS_TOTAL_ACTIVO"="V143","INGRESO_ANUAL_PASIVO_CIRCULANTE"="V144","INGRESO_ANUAL_SERVICIO_DEUDA"="V145",
                "TOTAL_PASIVO_TOTAL_ACTIVO"="V146","INMUEBLES_TOTAL_PASIVO"="V147","FECHA_VENCIMIENTO_DOCUMENTO_PAGARE"="V148","FECHA_VENCIMIENTO_ACTUAL_PAGARE"="V149","NUMERO_PRORROGAS_PAGARE"="V150","CODIGO_SECTOR_ECONOMICO"="V151","VACIO"="V152"
)

# ELIMINA LA NOTACION CIENTIFICA

options(scipen=999) 

# COLOCAR LOS FORMATOS A LAS VARIABLES

tod00$SALDO_ACTUAL <- gsub("[.]","",tod00$SALDO_ACTUAL)
tod00$SALDO_ACTUAL <- gsub(",",".",tod00$SALDO_ACTUAL)
tod00$SALDO_ACTUAL <- as.numeric(tod00$SALDO_ACTUAL)

tod00$MONTO_VENCIDO <- gsub("[.]","",tod00$MONTO_VENCIDO)
tod00$MONTO_VENCIDO <- gsub(",",".",tod00$MONTO_VENCIDO)
tod00$MONTO_VENCIDO <- as.numeric(tod00$MONTO_VENCIDO)

tod00$MONTO_INMOVILIZADO <- gsub("[.]","",tod00$MONTO_INMOVILIZADO)
tod00$MONTO_INMOVILIZADO <- gsub(",",".",tod00$MONTO_INMOVILIZADO)
tod00$MONTO_INMOVILIZADO <- as.numeric(tod00$MONTO_INMOVILIZADO)

tod11$SALDO_ACTUAL <- gsub("[.]","",tod11$SALDO_ACTUAL)
tod11$SALDO_ACTUAL <- gsub(",",".",tod11$SALDO_ACTUAL)
tod11$SALDO_ACTUAL <- as.numeric(tod11$SALDO_ACTUAL)

tod11$MONTO_VENCIDO <- gsub("[.]","",tod11$MONTO_VENCIDO)
tod11$MONTO_VENCIDO <- gsub(",",".",tod11$MONTO_VENCIDO)
tod11$MONTO_VENCIDO <- as.numeric(tod11$MONTO_VENCIDO)

tod11$MONTO_INMOVILIZADO <- gsub("[.]","",tod11$MONTO_INMOVILIZADO)
tod11$MONTO_INMOVILIZADO <- gsub(",",".",tod11$MONTO_INMOVILIZADO)
tod11$MONTO_INMOVILIZADO <- as.numeric(tod11$MONTO_INMOVILIZADO)

# IDENTIFICAR EL NOMBRE DEL CLIENTE

idt_cus <- select(tod00, ID, NOMBRE_CLIENTE) %>% group_by(ID) 

idt_cus$ID <- as.numeric(idt_cus$ID)

idt_nam <- mutate(idt_cus , VARIACION=ID-lead(ID,1))

idt_nam$MARCADOR <- ifelse(is.na(idt_nam$VARIACION),1,idt_nam$VARIACION)

idt_onl <- filter(idt_nam, MARCADOR == 1) %>% select(ID, NOMBRE_CLIENTE)

# IDENTIFICAR EL NOMBRE DEL GRUPO

idt_gru <- select(tod00, ID, ID_GRUPO_ECONOMICO, GRUPO_ECONOMICO) %>% group_by(ID) 

idt_gru$ID <- as.numeric(idt_gru$ID)

ig_nam <- mutate(idt_gru , VARIACION=ID-lead(ID,1))

ig_nam$MARCADOR <- ifelse(is.na(ig_nam$VARIACION),1,ig_nam$VARIACION)

ig_onl <- filter(ig_nam, MARCADOR == 1) %>% select(ID, ID_GRUPO_ECONOMICO, GRUPO_ECONOMICO)

# IDENTIFICA LOS PRODUCTOS A REALIZAR LA VARIACION 

td0 <- mutate(tod00, DIG1= str_sub(tod00$CUENTA_CONTABLE, 1, 1), 
              DIG2 = str_sub(tod00$CUENTA_CONTABLE, 4, 5), 
              MAR_CUEN=ifelse(DIG1==1 & DIG2=="02",1,
                              ifelse(DIG1==1 & DIG2=="11",1,
                                     ifelse(DIG1 != 1,1,
                                            ifelse(DIG1==1,0,""))))) %>%
  filter(DIG2==36 | DIG2==35)


td1 <- mutate(tod11, DIG1= str_sub(tod11$CUENTA_CONTABLE, 1, 1), 
              DIG2 = str_sub(tod11$CUENTA_CONTABLE, 4, 5), 
              MAR_CUEN=ifelse(DIG1==1 & DIG2=="02",1,
                              ifelse(DIG1==1 & DIG2=="11",1,
                                     ifelse(DIG1 != 1,1,
                                            ifelse(DIG1==1,0,""))))) %>%
  filter(DIG2==36 | DIG2==35)


# SE RELAIZA LA DEUDA TOTAL POR PROPUESTA 

p0 <- select(td0, PROPUESTA, ID, SALDO_ACTUAL) %>% group_by(PROPUESTA) %>% summarise(TOTALP_HOY=sum(SALDO_ACTUAL))

p1 <- select(td1, PROPUESTA, ID, SALDO_ACTUAL) %>% group_by(PROPUESTA) %>% summarise(TOTALP_AYER=sum(SALDO_ACTUAL))

# SE VALIDA QUE SEA UNA PROPUESTA NO TIENE SALDOS SOLO NOMBRES  

prp_idf <- select(td0, PROPUESTA, ID, NOMBRE_CLIENTE) 

prp_onl <- unique(prp_idf)

prp_idf1 <- select(td1, PROPUESTA, ID, NOMBRE_CLIENTE) 

prp_onl1 <- unique(prp_idf1)

# SE REALIZA LA UNION DE LOS NOMBRES Y LOS SALDOS POR PROPUESTA

pu <- full_join(p0, p1, by="PROPUESTA") %>% left_join(prp_onl, by="PROPUESTA") 

# SE COLOCA CERO A LAS VARIABLES QUE NO TIENEN VALORES

pu$TOTALP_HOY <- ifelse(is.na(pu$TOTALP_HOY),0,pu$TOTALP_HOY)
pu$TOTALP_AYER <- ifelse(is.na(pu$TOTALP_AYER),0,pu$TOTALP_AYER)

# SE CREA LA TABLA TOTAL

put <- mutate(pu, DIF_TOT=TOTALP_AYER-TOTALP_HOY) %>% arrange(desc(DIF_TOT)) %>% select(ID, NOMBRE_CLIENTE, PROPUESTA, TOTALP_HOY, TOTALP_AYER, DIF_TOT)

# SE UBICA SOLO EL PRESTAMO DE CAPITAL

td00 <- mutate(tod00, DIG1= str_sub(tod00$CUENTA_CONTABLE, 1, 1), 
               DIG2 = str_sub(tod00$CUENTA_CONTABLE, 4, 5), 
               MAR_CUEN=ifelse(DIG1==1 & DIG2=="02",1,
                               ifelse(DIG1==1 & DIG2=="11",1,
                                      ifelse(DIG1 != 1,1,
                                             ifelse(DIG1==1,0,""))))) %>%
  filter(DIG2==35)


td11 <- mutate(tod11, DIG1= str_sub(tod11$CUENTA_CONTABLE, 1, 1), 
               DIG2 = str_sub(tod11$CUENTA_CONTABLE, 4, 5), 
               MAR_CUEN=ifelse(DIG1==1 & DIG2=="02",1,
                               ifelse(DIG1==1 & DIG2=="11",1,
                                      ifelse(DIG1 != 1,1,
                                             ifelse(DIG1==1,0,""))))) %>%
  filter(DIG2==35)

# SE UBICA LA PROPUESTA POR EL SALDO DE CAPITAL 

p00 <- select(td00, PROPUESTA, ID, SALDO_ACTUAL) %>% group_by(PROPUESTA) %>% summarise(TOTALP_HOY=sum(SALDO_ACTUAL))

p11 <- select(td11, PROPUESTA, ID, SALDO_ACTUAL) %>% group_by(PROPUESTA) %>% summarise(TOTALP_AYER=sum(SALDO_ACTUAL))

# SE REALIZA LA UNION DE LOS NOMBRES Y LOS SALDOS POR PROPUESTA

pu11 <- full_join(p00, p11, by="PROPUESTA") %>% left_join(prp_onl, by="PROPUESTA") 

# SE COLOCA CERO A LAS VARIABLES QUE NO TIENEN VALORES

pu11$TOTALP_HOY <- ifelse(is.na(pu11$TOTALP_HOY),0,pu11$TOTALP_HOY)
pu11$TOTALP_AYER <- ifelse(is.na(pu11$TOTALP_AYER),0,pu11$TOTALP_AYER)

# SE CLASIFICA CADA OPERACION DEPENDIENDO DEL SALDO ANTERIOR Y ACTUAL

pu11 <- mutate(pu11, Dif=TOTALP_AYER-TOTALP_HOY, categoria= ifelse(TOTALP_AYER==0 & TOTALP_HOY>0, "LIQUIDADO",
                                                                   ifelse(TOTALP_AYER>0 & TOTALP_HOY==0, "CANCELADO",
                                                                          ifelse(TOTALP_AYER>0 & TOTALP_HOY>0 & Dif>0, "AMORTIZACION",
                                                                                 ifelse(TOTALP_AYER>0 & TOTALP_HOY>0 & Dif<0, "INCREMENTO","MANTIENE"))))) %>% arrange(desc(Dif)) %>% select(ID, NOMBRE_CLIENTE, PROPUESTA, TOTALP_HOY, TOTALP_AYER, Dif, categoria)

# SE CAMBIA EL NOMBRE DE LA VARIABLE

pu22 <- select(pu11, PROPUESTA, Dif, categoria) %>% rename("DIF_35"="Dif")

# UNIR LAS TABLAS POR PROPUESTA

put1 <- left_join(put, pu22, by="PROPUESTA" )

# ENCUENTRA LOS NOMBRES DE LOS CLIENTES CANCELADOS

put2 <- filter(put1, categoria == "CANCELADO") %>% select(PROPUESTA, TOTALP_HOY, TOTALP_AYER, DIF_TOT, DIF_35, categoria)

put3 <- left_join(put2, prp_onl1, by="PROPUESTA") %>% select(ID, NOMBRE_CLIENTE, PROPUESTA, TOTALP_HOY, TOTALP_AYER, DIF_TOT, DIF_35, categoria)

# SE UNE LOS CLIENTES CANCELADOS

put4 <- filter(put1, categoria != "CANCELADO" ) 

put5 <- rbind(put4, put3) %>% mutate(CANTIDAD=1, FECHA=fecha0$fecha0) %>% rename("CATEGORIA"="categoria")

# TOTAL DE LA VARIACION CON UNA TABLA DINAMICA SIMPLE DE LAS CATEGORIAS

var <- select(put5, CATEGORIA, DIF_TOT, CANTIDAD) %>% group_by(CATEGORIA) %>% summarise(TOTAL=sum(DIF_TOT),TOTAL_PROPUESTA=sum(CANTIDAD)) 

# TOTAL DE LA VARIACION CON UNA TABLA DINAMICA SIMPLE DE LAS CUENTAS

c0 <- select(td0, CUENTA_CONTABLE, SALDO_ACTUAL) %>% group_by(CUENTA_CONTABLE) %>% summarise('1'=sum(SALDO_ACTUAL)) 

# SE UBICA EL TOTAL DE LAS CUENTAS

ct0 <- data.frame("TOTAL"=colSums(c0[,2]))  

# SE CREA UNA NUEVA VARIABLE

cp0 <- select(td0, PROPUESTA, BANCO) %>% mutate(TOTAL="TOTAL_AHORA") 

cpu <- unique(cp0) 

# TOTAL DE LA VARIACION POR PROPUESTA 

cpu00 <- select(cpu, BANCO, TOTAL) %>% group_by(TOTAL) %>% summarise(TOTAL_PROPUESTA=sum(BANCO)) %>% rename("CATEGORIA"="TOTAL") 

# SE UNE LOS TOTAL DE SALDO Y POR PROPUESTA

th <- cbind(cpu00, ct0)

# EL MISMO PROCESO ANTERIOR CON EL OTRO ARCHIVO

c1 <- select(td1, CUENTA_CONTABLE, SALDO_ACTUAL) %>% group_by(CUENTA_CONTABLE) %>% summarise('1'=sum(SALDO_ACTUAL)) 

ct1 <- data.frame("TOTAL"=colSums(c1[,2]))  

cp1 <- select(td1, PROPUESTA, BANCO) %>% mutate(TOTAL="TOTAL_ANTERIOR") 

cpu1 <- unique(cp1) 

cpu11 <- select(cpu1, BANCO, TOTAL) %>% group_by(TOTAL) %>% summarise(TOTAL_PROPUESTA=sum(BANCO)) %>% rename("CATEGORIA"="TOTAL") 

ta <- cbind(cpu11, ct1)

# SE HACE LA UNION DE LAS TABLAS

total <- rbind(th, var, ta)

# SE CREA EL TITULO

titulo <- paste("DIA",fecha0[1,1])

cf0 <- rename(c0, {{titulo}}:="1")

# SE GENERA LOS ARCHIVOS EN EXCEL 

write.xlsx(total, paste('VARIACION',date0,'.xlsx'))

write.xlsx(put5, paste('VARIACION PROPUESTA',date0,'.xlsx'))

write.xlsx(cf0, paste('CUENTA CONTABLE',date0,'.xlsx'))